Azure/azure-functions-python-library

- azure/functions/_abc.py
- azure/functions/_eventhub.py
Azure/azure-functions-python-worker#288
> Add device_id property to EventHubEvent

- azure/functions/__init__.py
- azure/functions/_thirdparty/typing_inspect.py
- azure/functions/blob.py
- azure/functions/cosmosdb.py
- azure/functions/eventgrid.py
- azure/functions/eventhub.py
- azure/functions/http.py
- azure/functions/meta.py
- azure/functions/queue.py
- azure/functions/servicebus.py
- azure/functions/timer.py
Per Azure/azure-functions-python-worker#409, the rich binding
implementations are now in the library.
> Move rich binding implementations from the worker

- .gitignore
- tests/test_queue.py
I'm going to add some more tests. I just really like Python Azure Functions and want to make it better. Can we add a `dev` branch to the base repo for merging PRs?
> Add tests for QueueMessage

- azure/functions/eventhub.py
- azure/functions/meta.py
- setup.py
One half of fixing https://github.com/Azure/azure-functions-python-worker/issues/411. The other half is the worker change https://github.com/Azure/azure-functions-python-worker/pull/527.
> Handle eventhub cardinality

- azure/functions/meta.py
- tests/test_meta.py
Fixes https://github.com/Azure/azure-functions-python-worker/issues/460
> Additional parsing for fractional date times

- azure/functions/eventhub.py
- setup.py
Allow EventHub bindings to accept multiple events by defining List[func.EventHubEvent] parameter annotation
> Version 1.0.6

- setup.py
Allow Python 3.7 to mark param with enumerable annotation
> Version 1.0.7

- setup.py
1. Supports WSGI
2. Restore eventhub metadata for iothub events
3. Fix an issue where eventhub cardinality does not match the function context
> Version 1.1.0

- setup.py
Add supports for Python durable functions
> Version 1.2.0b1

- azure/functions/_abc.py
- azure/functions/_eventgrid.py
- azure/functions/_http.py
- azure/functions/_http_wsgi.py
- azure/functions/_utils.py
- azure/functions/blob.py
- azure/functions/cosmosdb.py
- azure/functions/eventhub.py
- azure/functions/http.py
- azure/functions/meta.py
- azure/functions/queue.py
- tests/test_code_quality.py
- tests/test_http.py
The mypy typing check has never been properly enabled since `azure.functions` is a package instead of a module. This is now fixed in code quality test.
resolves https://github.com/Azure/azure-functions-python-library/issues/44
> Fix mypy typing

- azure/functions/__init__.py
- setup.py
> Updating version to 1.2.1

- azure/functions/_abc.py
- azure/functions/_http_asgi.py
- azure/functions/_http_wsgi.py
- tests/test_http_asgi.py
- tests/test_http_wsgi.py
Added trace context and retry context properties to the context class
> Added trace and retry context properties

- azure/functions/_http_asgi.py
- azure/functions/extension/extension_meta.py
- azure/functions/kafka.py
- tests/test_kafka.py
Adding support for kafka headers :-
- Headers Kafka event should be able to read headers from metadata
> Adding Kafka headers to binding

- azure/functions/__init__.py
This reverts commit 7b4c53db42e4eab5d92a8d723e4d30cee2356985.
> Revert "Update __init__.py"

- setup.py
Change to removed tests dir from the wheel package
> Removed tests dir from wheel package

- CODEOWNERS
- README.md
Changes:
- Replaced checkmark with unicode
- Removed V2 from supported versions
> Updated readme to include unicode chars

- azure/functions/__init__.py
- azure/functions/_abc.py
- azure/functions/_sql.py
- azure/functions/sql.py
- tests/test_sql.py
This reverts commit 2518089284afaa82cd5cb1f53300a0430a5ced01.
Adding SQL Binding support back
> Revert "Revert "Add SQL Binding support (#124)""

- azure/functions/_http_asgi.py
> Warning should specify to await handle_async

- README.md
added information of newer supported versions.
> Information of newer supported versions.

- azure/functions/decorators/function_app.py
- docs/ProgModelSpec.pyi
- tests/decorators/test_function_app.py
Updated blueprints to include settings api
> Added SettingsApi to Blueprints

- azure/functions/_http_asgi.py
Removing debug logging from asgi handlers.
> Removing debug logs

- azure/functions/__init__.py
Update azure-functions to 1.19.0
> Update to 1.19.0

- azure/functions/__init__.py
- azure/functions/decorators/blob.py
- tests/decorators/test_blob.py
- tests/decorators/test_decorators.py
Releasing 1.21.1 without mysql changes.
> build: update Python Library Version to 1.21.1
