Azure/azure-functions-python-library

azure/functions/__init__.py, azure/functions/_http.py
To ease testing, allow creating instances of `HttpRequest`.
Fixes: https://github.com/Azure/azure-functions-python-worker/issues/262
=> Make it possible to make an instance of HttpRequest

azure/functions/_http.py
Missing trailing `:` for the `url` parameter causes the docstring to render improperly by including `:param str url HTTP URL.` in https://docs.microsoft.com/en-us/python/api/azure-functions/azure.functions.httprequest?view=azure-python and not listing `url` as a parameter.
Closes #19
=> Fix a docstring formatting typo

azure/functions/_servicebus.py, azure/functions/servicebus.py, setup.py
Pulled in changes from TestPyPi to the following PR to test with worker: https://github.com/Azure/azure-functions-python-worker/pull/544
=> Service bus delivery count

azure/functions/cosmosdb.py, tests/test_cosmosdb.py
Resolve https://github.com/Azure/azure-functions-python-worker/issues/548
Allow customer to fetch **null** value from DocumentList parameter when using CosmosDB trigger.
=> Allow cosmosdb document parameter to pass in null

azure/functions/eventhub.py
Resolves https://github.com/Azure/azure-functions-python-worker/issues/589
@jeffhollan mentioned that since we start supporting **cardinality** function settings, we should allow user to take in
- List[func.EventHubEvent] for **cardinality=many**
- func.EventHubEvent for **cardinality=one**
=> Allow azure functions to take in List[EventHubEvent]

azure/functions/eventhub.py, tests/test_cosmosdb.py, tests/test_eventhub.py, tests/test_http.py, tests/test_queue.py
Since Python 3.7 change the implementation of generic type.
Now all the generic types (e.g. List, Set) are instantiated from **_GenericAlias** (previously in Python 3.6, they are instantiated from **type**). Thus, this affects all **issubclass** module usage because **List** and **Set** are not classes anymore.
To solve this issue, we get the generic type info from tp.\_\_origin\_\_ in Python 3.7.
=> Allow Python 3.7 to use List[func.EventHubEvent]

azure/functions/_utils.py, azure/functions/meta.py, tests/test_meta.py
Resolves https://github.com/Azure/azure-functions-python-worker/issues/591
The Azure Media Service for EventGrid trigger metadata's event_time is a local time, which is not in ISO 8601 format. This PR fixes the local time parsing issue.
=> Fix local time parsing

.flake8, azure/functions/eventhub.py, tests/test_eventhub.py
Resolves https://github.com/Azure/azure-functions-python-worker/issues/418
1. Fix a parsing issue where the iothub metadata is not handled properly. The iothub_metadata does not exist in trigger_metadata, instead, it is placed in **SystemProperties (cardinality = one)** and **SystemPropertiesArray (cardinality = many)**
2. Fix an issue where the IoTHub event messages are treated as single message. Since the message format is `json`, thus, it is handled with `decode_single_event`. This PR will make sure the cardinality is handled correctly.
=> Restore IoTHub metadata in EventHub

azure/functions/py.typed, setup.py
resolves: https://github.com/Azure/azure-functions-python-library/issues/43
Adding the py.typed marker in azure.functions library
[PEP 561](https://www.python.org/dev/peps/pep-0561/#packaging-type-information)
=> [PEP 561] add py.typed in azure.functions

azure/functions/__init__.py, azure/functions/_http_wsgi.py, tests/test_http_wsgi.py
This feature is migrated from @vtbassmatt 's **[azf-wsgi](https://github.com/vtbassmatt/azf-wsgi)** project which enables wsgi feature for Azure Functions Python app. We've contacted @vtbassmatt and agreed to implement this feature on azure-functions-python-library. We greatly appreciate his contribution, helping us expand the Python user base in his own time.
1. Override the main entrypoint
```python
import logging
import azure.functions as func
from ..FlaskApp.wsgi import application
main = func.WsgiMiddleware(application).main
```
2. Alternatively, use the old syntax as demonstrated in **[azf-wsgi](https://github.com/vtbassmatt/azf-wsgi)**
```python
import logging
import azure.functions as func
from ..FlaskApp.wsgi import application
def main(req: func.HttpRequest, context: …
```
=> Enable WSGI for Python Function App

azure/functions/__init__.py, azure/functions/_abc.py, azure/functions/_durable_functions.py, azure/functions/durable_functions.py, azure/functions/meta.py, tests/test_durable_functions.py, tests/test_http.py
To support durable function running in Python Worker, we should create a rich binding for OrchestrationTrigger
1. Added an OrchestrationContext type for accepting orchestrate context
2. Allow user code to use `orchestration_context.body` to access the orchestration data
3. Set `has_implicit_output=True` for OrchestrationTrigger to enable context return even when `$return` is not defined in function.json
```javascript
// function.json
{
"scriptFile": "__init__.py",
"bindings": [
{
"name": "orctx",  //context is a reserved keyword in azure functions Python, we use context to pass the function_name and invocation_id to our customers
"type": "orchestrationTrigger",
"direction": "in"
// remove datatype here
}
],
"disabled": false
}
```
```python
import azure.functions as func
def main(orctx: …
```
=> Add orchestration trigger for durable functions

azure/functions/durable_functions.py, tests/test_durable_functions.py
https://github.com/Azure/azure-functions-python-worker/pull/643
Previously, the Activity Trigger in Python Durable Functions only supports string as return value. Now, we should support JSON serializable Python primitive types.
✔string, int, float, bool, list of string/int/float/bool, dictionary of string/int/float/bool, None
❌set, frozenset, bytes, bytearray, custom type, custom dataclass
=> Add activity trigger encode/decode logic for durable function

azure/functions/__init__.py, setup.py, tests/test_code_quality.py
Customer should be able to query the version of the library they are currently using. According to PEP 440, __version__ is recommended to be part of the library.
resolves: https://github.com/Azure/azure-functions-python-library/issues/52
=> Add func.__version__ dunder method (PEP 440)

azure/functions/__init__.py, azure/functions/_durable_functions.py, azure/functions/durable_functions.py
This PR is a kind of "follow-up" to: https://github.com/Azure/azure-functions-python-library/pull/53
The Durable Functions Python group is looking to support custom objects as inputs and outputs for their Orchestrations and Activity Functions. To do this, we establish a kind of "contract" with the user that their custom classes will provide static `to_json` and `from_json` methods that we can use to serialize and deserialize their object instances. These functions get called as `json.dumps` and `json.loads` 'callbacks` at various points and throughout the library and the [durable-python ](https://github.com/Azure/azure-functions-durable-python) code itself.
So this PR does three things:
1) It defines the helper methods to serialize and de-serialize custom objects
2) Uses them in the …
=> Adds Encode and Decode logic for "arbitrary" objects for Durable Python

.flake8, .gitignore, azure/functions/__init__.py, azure/functions/_abc.py, azure/functions/_eventgrid.py, azure/functions/eventgrid.py, tests/test_eventgrid.py
Adding support for event_grid's output binding support.
=> Adding event grid's output binding and updating gitignore

azure/functions/_eventhub.py, azure/functions/_servicebus.py, azure/functions/eventhub.py, azure/functions/meta.py, azure/functions/servicebus.py, tests/test_eventhub.py, tests/test_meta.py, tests/test_servicebus.py
https://github.com/Azure/azure-functions-python-worker/issues/693
Due to the constant change in extension schema, it is pretty hard for us to keep updating the rich type bindings (e.g. Node worker never do that, they always pass json to their customer). We should expose the **metadata** field to our customer, with a json inside.
Reconstruct meta.Datum item into Python object using **python_value** and **python_type** field. Cache it into a variable **_trigger_metadata_pyobj**. Expose **metadata** field to customer for Python dictionary access.
**Note**
GRPC collection_string and GRPC collection_sint64 will be serialized into json array.
GRPC Bytes and GRPC collection_bytes will be based64 encoded.
For EventHub and IoTHub event, user now have access to **metadata** field, which is a Python …
=> Expose metadata field in servicebus and eventhub

azure/functions/__init__.py, azure/functions/_kafka.py, azure/functions/kafka.py, setup.py, tests/test_kafka.py
This pull request includes Kafka extension with unit testing. 
Could you have a look, please?
I tested on the Kafka extension repo for these scenarios. 
* Local Kafka Cluster
* Confluent Cloud (Managed Kafka Cluster)
* Cardinality One and Many scenarios
* data_type as string and binary
* Linux/Windows Premium plan
The sample functions and environment, you can find it on this PR. 
The PR includes the same kafka.py, with devcontainer that starts Kafka cluster and documentation in here.
https://github.com/Azure/azure-functions-kafka-extension/pull/140
Once this PR has been merged and published to pip repo. I will change the https://github.com/Azure/azure-functions-kafka-extension repo to reference this library.
=> Kafka extension implementation

azure/functions/_servicebus.py, azure/functions/eventhub.py, tests/test_eventhub.py, tests/test_servicebus.py
1. The single EventHub enqueue_time field now extract data from `trigger_metadata['EnqueuedTimeUtc']` instead of `trigger_metadata['EnqueuedTime']`.
2. The newly introduced ServiceBus properties **expires_at_utc** and **enqueued_time_utc** need to be exposed at _servicebus.py public interface.
3. Add more robust tests in EventHub event properties and ServiceBus message properties.
=> Fix EnqueueTimeUtc in EventHub and expose ServiceBus new properties 

azure/functions/blob.py, tests/test_blob.py
Resolves https://github.com/Azure/azure-functions-python-library/issues/39
Resolves https://github.com/Azure/azure-functions-python-worker/issues/670 
Original PR: https://github.com/Azure/azure-functions-python-library/pull/40 
When a blob does not exist, the blob input binding will raise an exception. Asked by the issues mentioned above, we should simply return a None object in the input binding since it is not a customer error.
1. The Blob input binding will now return None if the blob does not exist
2. Add unit testing for blob trigger
=> Input binding returns null when blob does not exist

azure/functions/__init__.py
I automated this PR by using [yesqa](https://github.com/asottile/yesqa) -- I'm also the maintainer of flake8
if a name is present in the `__all__` sequence, then you don't need to ignore the import with `# noqa`
=> remove unneeded noqa comments

azure/functions/_http_asgi.py, azure/functions/_http_wsgi.py, tests/test_http_asgi.py, tests/test_http_wsgi.py
Fix: https://github.com/Azure/azure-functions-python-library/issues/71
Fix: https://github.com/Azure/azure-functions-python-worker/issues/839
1. Now when the WSGI and ASGI middleware start, we will emit `Instantiating Azure Functions ASGI middleware.` or `Instantiating Azure Functions WSGI middleware.` log message for the very first time when the middleware instantiated either in `main = WsgiMiddleware(app)` syntax or `def func(req, context): return WsgiMiddleware(app).handle(req, context)` syntax.
2. Fix an issue where the middlewares fail to accept the context parameter.
1. In the worker, we need to direct `azure.functions` log into system log category.
cc: @tonybaloney @stefanushinardi @vrdmr
=> Add message when ASGI and WSGI is enabled

setup.py
This is the root cause of the library where the azure.functions._thirdparty sub-folder failed to reload properly.
The dangling _thirdparty folder is not being treated as a proper Python module.
Thus, when poping out from `sys.modules`, it is not being recognized as a part of azure.functions. Thus, the topology graph is not built out correctly when removing caches from sys.modules.
https://github.com/Azure/azure-functions-python-worker/pull/854
It has \_\_init__.py file defined in it: https://github.com/Azure/azure-functions-python-worker/tree/dev/azure_functions_worker/_thirdparty
It is being included in setup.py: https://github.com/Azure/azure-functions-python-worker/blob/dev/setup.py#L389
Using this following code for reloading module.
```python
try:
module_paths = set(getattr(module, …
```
=> Fix an issue where the _thirdparty package is not distributed correctly

.github/workflows/gh-tests-ci.yml, CODEOWNERS, README.md, setup.py
Excluded azure from the packages. This fixes an issue where the azure functions version does not get updated when a version is specified in the functions requirements.txt file.
Reason for this is since azure directory has an __init.py__ file, including azure in the package build overrides the users dependencies.
=> Exclude azure from package build

azure/functions/_http.py, azure/functions/_http_asgi.py
It seems `HttpResponse` is the only class in this file that does not contain type hints.
This generates errors when client code is checked using `mypy` in strict mode:
```
error: Call to untyped function "HttpResponse" in typed context
```
Add type hints following the docstring.
=> Add type hints to `HttpResponse`

azure/functions/_http_wsgi.py
I believe that the environ PATH_INFO attribute should be unquoted when it is passed through. This is replicates the functionality of Gunicorn (https://github.com/pallets/werkzeug/blob/5a2bf35441006d832ab1ed5a31963cbc366c99ac/werkzeug/serving.py#L98) and Werkzeug (https://github.com/benoitc/gunicorn/blob/cf55d2cec277f220ebd605989ce78ad1bb553c46/gunicorn/http/wsgi.py#L184)
There is a more detailed explanation of this in the Gunicorn project - https://github.com/benoitc/gunicorn/pull/1211 - but in short PEP 333 implicitly describes restructuring the url - https://www.python.org/dev/peps/pep-3333/#url-reconstruction.
The reason for raising this is that I have a Flask app which exhibits different behaviour when running under Azure Functions via the wsgi middleware. I have raised the PR to …
=> WSGI middleware should unquote path_info 

azure/functions/_http_asgi.py, tests/test_http_asgi.py
Fixes 
https://github.com/developmentseed/titiler/issues/388 
https://github.com/encode/starlette/issues/1320
https://github.com/Azure/azure-functions-python-worker/issues/903
=> ASGI worker: Yield a `http.disconnect` on any additional receive calls

azure/functions/timer.py, tests/test_timer.py
Added missing fields in timer object. 
Fixes: https://github.com/Azure/azure-functions-python-worker/issues/681
Fixes: https://github.com/Azure/azure-functions-python-worker/issues/858
=> Add missing fields in timer object.

azure/functions/_cosmosdb.py, tests/test_cosmosdb.py
Change to address BUG: Cosmos DB Document should not be filtering _ts  address  https://github.com/Azure/azure-functions-python-library/issues/120
=> remove internal cosmosdb keys filtering

azure/functions/decorators/function_app.py, docs/ProgModelSpec.pyi, tests/decorators/test_decorators.py, tests/decorators/test_function_app.py
Changes involving:
1. FunctionApp __init__ auth_level -> http_auth_level
2. FunctionApp __init__  remove app_kwargs
3. FunctionApp __init__ change asgi_app/wsgi_app to kwargs
4. Remove data type from route
5. Change all trigger decorators to noun naming
=> Address pyspec feedback for new programming model

azure/functions/decorators/blob.py, azure/functions/decorators/core.py, azure/functions/decorators/cosmosdb.py, azure/functions/decorators/custom.py, azure/functions/decorators/eventhub.py, azure/functions/decorators/function_app.py, azure/functions/decorators/generic.py, azure/functions/decorators/http.py, azure/functions/decorators/queue.py, azure/functions/decorators/servicebus.py, azure/functions/decorators/timer.py, azure/functions/decorators/utils.py, docs/ProgModelSpec.pyi, tests/decorators/test_blob.py, tests/decorators/test_core.py, tests/decorators/test_cosmosdb.py, tests/decorators/test_custom.py, tests/decorators/test_decorators.py, tests/decorators/test_eventhub.py, tests/decorators/test_function_app.py, tests/decorators/test_generic.py, tests/decorators/test_http.py, tests/decorators/test_queue.py, tests/decorators/test_servicebus.py, tests/decorators/test_timer.py, tests/decorators/test_utils.py
Add custom trigger, input and output bindings.
=> Add generic binding decorators/Modify existing decorators to enable decorator extensibility under new programming model

azure/functions/_abc.py, azure/functions/_http.py, azure/functions/http.py, tests/test_http.py, tests/test_http_wsgi.py
Part of change to address https://github.com/Azure/azure-functions-python-library/issues/107
Related change in worker: https://github.com/Azure/azure-functions-python-worker/pull/1004
1. Make HttpResponseHeader inherit from werkzeug header class which is also used in Flask, the header class has dict-like interface but is ordered and can store the same keys multiple times, all operations are case insensitive on header key.
2. Cookie headers are extracted from httpresponseheaders and sent to worker as cookie field in rpchttp message.
=> Fix for GH#107: Enable support for multiple Set-Cookie response headers (native & wsgi/asgi)

azure/functions/meta.py
This is to fix abc abstractclassmethod deprecation
=> replace abstractclassmethod with abstract/class method

azure/functions/http.py, tests/test_http.py
Skipping setting multiple Set-Cookie headers as SimpleCookie which is a standard python lib api in python3.7 does not support samesite attribute and would cause cookie parsing error. (Ref: https://docs.python.org/3/library/http.cookies.html). A warning will be given to customers who uses python3.7 and tries to set multiple cookie headers.
=> GH#107: Skip setting multi Set-Cookie headers for python 3.7

azure/functions/decorators/function_app.py, docs/ProgModelSpec.pyi, tests/decorators/test_decorators.py
All input and output binding names are suffixed with _input and _output.
=> Binding name updates

azure/functions/kafka.py, tests/test_kafka.py
We were retrieving the key value for the case of multi-event from the already retrieved data, due to which customer was facing the crash in their basic scenario.
Customer has raised this issue multiple times -- https://github.com/Azure/azure-functions-kafka-extension/issues/388
=> Fixing the Key decode issue for multi-events 

azure/functions/blob.py, tests/test_blob.py
Implementing read1 method for InputStream which enables support for libraries like pandas to pass InputStream Directly.
Fixes: https://github.com/Azure/azure-functions-python-library/issues/92
=> Implement read1 method for InputStream

.github/workflows/gh-tests-ci.yml
3.6 isn't supported on Azure Functions anymore and 3.11 is planned for release soon
=> Drop 3.6 and add 3.11 to test matrix

azure/functions/_http_asgi.py, azure/functions/decorators/function_app.py, azure/functions/decorators/utils.py
https://github.com/Azure/azure-functions-python-worker/issues/1161
=> Fix callable type hint in v2

.github/workflows/gh-tests-ci.yml, azure/functions/_abc.py, azure/functions/_sql.py, azure/functions/sql.py, tests/test_sql.py
Moved sqlrow from _abc to sql.py
=> Moved SqlRow from _abc

azure/functions/decorators/function_app.py, tests/decorators/test_decorators.py
=> Adding timer_trigger with schedule as an alias

azure/functions/_http.py, tests/test_http.py
It should be possible to pass values from the standard library http.HTTPStatus enum to HTTPResponse
=> Added support for http.HTTPStatus in HTTPResponse

azure/functions/decorators/cosmosdb.py, azure/functions/decorators/function_app.py, tests/decorators/test_cosmosdb.py, tests/decorators/test_decorators.py
Added support for cosmos db v4 extension for the new programming model.
New decorators for cosmosdb:
Extension 2.x and 3.x 
- cosmos_db_trigger_v3
- cosmos_db_input_v3
- cosmos_db_output_v3
Extension 4.x and above
- cosmos_db_trigger 
- cosmos_db_input
- cosmos_db_output
The new v4 cosmos db extension installation can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2?tabs=in-process%2Cextensionv4&pivots=programming-language-python#install-bundle)
The latest support configurations for the new programming model can be found [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-cosmosdb-v2-input?tabs=python-v2%2Cin-process%2Cextensionv4&pivots=programming-language-python#configuration)
=> Added support for CosmosDB v4 extension

azure/functions/extension/app_extension_base.py, azure/functions/extension/extension_meta.py, azure/functions/extension/function_extension_exception.py
Besides, fixed some obvious spelling mistakes in the same module.
=> Fixed some unclear definition docs in AppExtensionBase

azure/functions/decorators/__init__.py, azure/functions/decorators/function_app.py, tests/decorators/test_function_app.py
Hotfix for missing import of ExternalHttpFunctionApp class in lib version 1.14.0
=> Add ExternalHttpFunctionApp

azure/functions/decorators/core.py, azure/functions/decorators/function_app.py, azure/functions/decorators/utils.py, tests/decorators/test_decorators.py
Fix for a rising incident that function app restarted as synctrigger calls fail due to inconsistent hash values every time function host calls /admin/synctriggers to get worker function app metadata.
=> preserve pystein function app metadata key order

README.md
Updated to reflect support status as per https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=isolated-process%2Cv4&pivots=programming-language-python#languages
=> Updated supported versions as per Function App learn.microsoft.com documentation

azure/functions/_abc.py, azure/functions/_servicebus.py, azure/functions/servicebus.py, tests/test_servicebus.py
Fixes: https://github.com/Azure/azure-functions-pyfx-planning/issues/123
=> ServiceBus Extension Parity to .NET

azure/functions/durable_functions.py, tests/test_durable_functions.py
Created a DurableClient converter class based off of the Generic converter type so that DurableClient is no longer a generic type. Only function needed was has_implicit_output
=> DurableClient Converter

azure/functions/decorators/blob.py, azure/functions/decorators/function_app.py, docs/ProgModelSpec.pyi, tests/decorators/test_blob.py, tests/decorators/test_decorators.py
Previously, the source param was required and set to a default value of `BlobSource.LOGS_AND_CONTAINER_SCAN`. This caused an error when indexing the blob trigger function saying: 
```Could not convert 'LOGS_AND_CONTAINER_SCAN' to BlobTriggerSource. Error converting value "LOGS_AND_CONTAINER_SCAN" to type 'Microsoft.Azure.WebJobs.BlobTriggerSource'. Path 'source', line 1, position 184. Requested value 'LOGS_AND_CONTAINER_SCAN' was not found.```
This fix addresses that issue.
=> Optional source param for blob trigger

eng/templates/build.yml, eng/templates/ci-tests.yml
Removed pool specification so that build and unit tests templates can be used for both official and public builds.
=> 1ES build fixes

azure/functions/decorators/eventgrid.py, azure/functions/decorators/function_app.py, tests/decorators/test_eventgrid.py
Added connection property to the eventgrid trigger.
Connection property is needed to use MI with eventgrid.
Ref: https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-output?tabs=python-v2%2Cisolated-process%2Cnodejs-v4%2Cextensionv3&pivots=programming-language-python#identity-based-authentication
Event grid output binding decorator will have a connection arg. 
Function app can now have `connection`  or  a combination of `TopicKeySetting` and `TopicEndpointUri` but not both.
```
@app.event_grid_output(
arg_name="outputEvent",
topic_endpoint_uri="AzureWebJobsEventGridTopicUri",
topic_key_setting="AzureWebJobsEventGridConnectionKey")
```
OR 
```
@app.event_grid_output(
arg_name="outputEvent",
connection="AzureWebJobsEventGridTopicUri")
```
Fixes: …
=> Added eventgrid connection property

eng/templates/official/jobs/build-artifacts.yml
Previously, builds were done using a windows image. This resulted in the following warning messages when doing the builds: 
`ValueError: underlying buffer has been detached`
Changing to use a linux image resolves this.
Error:
`
File "D:\a\_work\1\s\setup.py", line 23, in <module>
setup(
File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\setuptools\__init__.py", line 87, in setup
return distutils.core.setup(**attrs)
File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
return run_commands(dist)
File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
dist.run_commands()
File "C:\hostedtoolcache\windows\Python\3.11.9\x64\Lib\site-packages\s …
=> Changed builds to use linux image

.github/workflows/label.yml
Currently prs from forked pr will not have write access to run this action. Ex. https://github.com/Azure/azure-functions-python-library/pull/243 Making changes to allow that https://github.com/actions/labeler?tab=readme-ov-file#permissions
=> chore: allow forked pr to run labeler pipeline

azure/functions/__init__.py, azure/functions/_mysql.py, azure/functions/mysql.py, tests/test_mysql.py
Adding MySql Decorators V1 model
=> feat: Add MySql Binding Support V1

azure/functions/decorators/blob.py, tests/decorators/test_blob.py, tests/decorators/test_decorators.py
**Change to be incorporated in 1.21.1.**
When defining a BlobTrigger using `BlobSource.EVENT_GRID`, the source value was not being resolved correctly, and the error below was being thrown. This is because the host was receiving `EVENT_GRID` as the source value, instead of the correct value `"EventGrid"`. This changes what source is set to in the `BlobTrigger` decorator. If source is defined, source is set to the `EVENT_GRID` value. If source is not defined, source is set to null and is ignored.
```
@app.blob_trigger(arg_name="myblob",
path="mycontainer",
data_type=func.DataType.STRING,
source = func.BlobSource.EVENT_GRID,
connection="AzureWebJobsStorage") 
```
```
The 'blob_trigger' function is in error: Unable to configure binding 'myblob' of type 'blobTrigger'. This may indicate invalid …
```
=> fix: value resolution for BlobSource.EVENT_GRID
